In [5]:
import yfinance as yf
import pandas as pd
import datetime as dt

### Price Data

In [6]:
#Retrieving Data
ticker = 'CBA.AX'
start = dt.date.today() - dt.timedelta(1095) #2 year range
end = dt.date.today()

df= yf.download(ticker, start, end)

[*********************100%***********************]  1 of 1 completed

In [77]:
#Return specific date range
df_date_range = df.loc['2018-01-01':'2018-12-31']
df_date_range

#Return conditional data - 2019 data
df_filter = df.reset_index()
df_filter = df_filter[df_filter['Date'].dt.year == 2019] 
df_filter

          Date       Open       High        Low      Close  Adj Close   Volume
146 2019-01-02  72.349998  72.470001  70.769997  70.970001  63.507668  2858639
147 2019-01-03  71.250000  71.980003  70.860001  71.839996  64.286179  3345567
148 2019-01-04  71.500000  71.959999  71.080002  71.889999  64.330940  3501951
149 2019-01-07  72.500000  72.989998  72.449997  72.570000  64.939438  2615597
150 2019-01-08  72.379997  72.800003  72.004997  72.470001  64.849953  2363648
..         ...        ...        ...        ...        ...        ...      ...
394 2019-12-23  81.190002  81.300003  80.750000  80.839996  76.594879  1317871
395 2019-12-24  80.720001  80.849998  80.400002  80.709999  76.471710   783104
396 2019-12-27  80.989998  81.120003  80.550003  81.070000  76.812805  1159836
397 2019-12-30  81.250000  81.300003  80.470001  81.099998  76.841225   905155
398 2019-12-31  80.529999  80.550003  79.800003  79.900002  75.704239  1766363

[253 rows x 7 columns]

### Fundamentals

In [32]:
from yahoofinancials import YahooFinancials

#Retrieving data
ticker_financials = YahooFinancials(ticker)
ticker_summary = ticker_financials.get_summary_data()

In [33]:
#Organising data
ticker_summary_df = pd.DataFrame(ticker_summary)
ticker_summary_df

                                    CBA.AX
algorithm                             None
ask                                 101.21
askSize                               7100
averageDailyVolume10Day            1877907
averageVolume                      2372783
averageVolume10days                1877907
beta                              0.678828
bid                                 101.19
bidSize                              36400
circulatingSupply                     None
currency                               AUD
dayHigh                             101.91
dayLow                              100.94
dividendRate                          2.48
dividendYield                       0.0244
exDividendDate                  2021-02-16
expireDate                               -
fiftyDayAverage                    95.3092
fiftyTwoWeekHigh                    102.64
fiftyTwoWeekLow                      62.64
fiveYearAvgDividendYield              5.31
forwardPE                          18.2599
fromCurrency                          None
lastMarket                            None
marketCap                     179290931200
maxAge                                   1
maxSupply                             None
navPrice                              None
open                                101.38
openInterest                          None
payoutRatio                         0.8109
previousClose                       101.48
priceHint                                2
priceToSalesTrailing12Months       8.45194
regularMarketDayHigh                101.91
regularMarketDayLow                 100.94
regularMarketOpen                   101.38
regularMarketPreviousClose          101.48
regularMarketVolume                 743121
startDate                                -
strikePrice                           None
toCurrency                            None
totalAssets                           None
tradeable                            False
trailingAnnualDividendRate            2.48
trailingAnnualDividendYield      0.0244383
trailingPE                          22.475
twoHundredDayAverage               87.4032
volume                              743121
volume24Hr                            None
volumeAllCurrencies                   None
yield                                 None
ytdReturn                             None

In [34]:
#Retrieving balance sheet data
ticker_balance = ticker_financials.get_financial_stmts('annual', 'balance')

In [30]:
#Organising balance sheet sata
ticker_balance_eda = ticker_balance['balanceSheetHistory'][ticker][0]
ticker_balance_eda_df = pd.DataFrame(ticker_balance_eda) 
ticker_balance_eda_df

                                 2020-06-30
accountsPayable                685219000000
cash                            27307000000
commonStock                     38282000000
deferredLongTermAssetCharges     2060000000
goodWill                         5284000000
intangibleAssets                 1660000000
longTermDebt                   150544000000
longTermInvestments             87850000000
minorityInterest                    5000000
netReceivables                   3018000000
netTangibleAssets               65064000000
otherAssets                    778475000000
otherCurrentAssets              11096000000
otherCurrentLiab                 9681000000
otherLiab                        5455000000
otherStockholderEquity           2666000000
propertyPlantEquipment           5602000000
retainedEarnings                31211000000
shortLongTermDebt               18764000000
shortTermInvestments            16858000000
totalAssets                   1014060000000
totalCurrentAssets             135189000000
totalCurrentLiabilities        783479000000
totalLiab                      942047000000
totalStockholderEquity          72008000000
treasuryStock                    2515000000

### Cryptocurrency Price Data

In [36]:
#Retrieving Data
coin = 'eth-usd'

coin_financials = YahooFinancials(coin)
coin_summary = coin_financials.get_summary_data()

#Organising Data
coin_summary_df = pd.DataFrame(coin_summary)
coin_summary_df

                                    ETH-USD
algorithm                              None
ask                                    None
askSize                                None
averageDailyVolume10Day         29176773939
averageVolume                   35767158563
averageVolume10days             29176773939
beta                                   None
bid                                    None
bidSize                                None
circulatingSupply                 116215616
currency                                USD
dayHigh                             2520.21
dayLow                               2412.2
dividendRate                           None
dividendYield                          None
exDividendDate                            -
expireDate                                -
fiftyDayAverage                     2931.53
fiftyTwoWeekHigh                    4362.35
fiftyTwoWeekLow                     219.473
fiveYearAvgDividendYield               None
forwardPE                              None
fromCurrency                            ETH
lastMarket                    CoinMarketCap
marketCap                      283303706624
maxAge                                    1
maxSupply                              None
navPrice                               None
open                                2520.21
openInterest                           None
payoutRatio                            None
previousClose                       2520.21
priceHint                                 2
priceToSalesTrailing12Months           None
regularMarketDayHigh                2520.21
regularMarketDayLow                  2412.2
regularMarketOpen                   2520.21
regularMarketPreviousClose          2520.21
regularMarketVolume             37571510272
startDate                        2015-08-07
strikePrice                            None
toCurrency                            USD=X
totalAssets                            None
tradeable                             False
trailingAnnualDividendRate             None
trailingAnnualDividendYield            None
twoHundredDayAverage                1752.49
volume                          37571510272
volume24Hr                      37571510272
volumeAllCurrencies             37571510272
yield                                  None
ytdReturn                              None

In [38]:
#Cryptocurrency historical price data
coin_price_historical = coin_financials.get_historical_price_data(start.isoformat(), end.isoformat(), 'monthly')

#Organising data
coin_price_data = coin_price_historical['ETH-USD']['prices']
coin_price_data_df = pd.DataFrame(coin_price_data)
coin_price_data_df

,date,high,low,open,close,volume,adjclose,formatted_date
0,1530399600,513.432983,422.809998,455.242004,433.867004,52395320112,433.867004,2018-06-30
1,1533078000,435.457001,254.649994,433.868988,283.003998,49073240000,283.003998,2018-07-31
2,1535756400,301.144012,170.257004,283.496002,232.848007,55203910000,232.848007,2018-08-31
3,1538348400,234.145004,188.707001,233.220001,197.380997,44459810000,197.380997,2018-09-30
4,1541030400,221.651993,101.769997,197.537003,113.171417,59375107547,113.171417,2018-11-01
5,1543622400,157.668701,82.829887,113.397758,133.368256,72329895639,133.368256,2018-12-01
6,1546300800,160.824890,103.336464,133.418152,107.061012,85054975141,107.061012,2019-01-01
7,1548979200,165.549622,102.934563,107.147682,136.746246,101430995445,136.746246,2019-02-01
8,1551398400,149.613235,125.402702,136.836243,141.514099,138882123600,141.514099,2019-03-01
9,1554073200,184.377853,140.737564,141.465485,162.166031,204556824026,162.166031,2019-03-31
10,1556665200,287.201630,159.660217,162.186554,268.113556,314349041886,268.113556,2019-04-30
11,1559343600,361.398682,229.257431,268.433350,290.695984,270589672710,290.695984,2019-05-31
12,1561935600,318.223114,193.990417,290.268494,218.654144,249663340219,218.654144,2019-06-30
13,1564614000,239.115906,167.071411,218.554596,172.469788,203391541658,172.469788,2019-07-31
14,1567292400,222.871689,157.130325,172.458405,179.872208,223404691299,179.872208,2019-08-31
15,1569884400,195.942505,157.463425,180.209122,183.966919,251679512754,183.966919,2019-09-30
16,1572566400,193.547256,133.802338,183.803696,152.539688,252844958892,152.539688,2019-11-01
17,1575158400,153.155396,119.780060,152.491928,129.610855,247117483830,129.610855,2019-12-01
18,1577836800,186.260483,126.490021,129.630661,180.160172,327976431869,180.160172,2020-01-01
19,1580515200,287.123688,179.745178,180.113770,219.848511,578092481246,219.848511,2020-02-01
20,1583020800,249.978485,95.184303,219.752686,133.593567,498921414458,133.593567,2020-03-01
21,1585695600,227.529694,129.730942,133.612320,207.602051,515444186301,207.602051,2020-03-31
22,1588287600,244.045258,180.718338,207.901733,230.975708,505593287696,230.975708,2020-04-30
23,1590966000,252.222000,219.472672,230.860260,226.315002,252220724156,226.315002,2020-05-31
24,1593558000,348.611359,224.544495,226.134583,345.554657,251431946993,345.554657,2020-06-30
25,1596236400,444.577759,343.587433,345.798615,435.079742,374122796720,435.079742,2020-07-31
26,1598914800,487.211884,316.774353,434.874451,360.022369,503460977506,360.022369,2020-08-31
27,1601506800,420.141663,335.533600,360.004639,386.590332,360623040866,386.590332,2020-09-30
28,1604188800,621.173401,371.312744,386.590332,614.842529,487476388045,614.842529,2020-11-01
29,1606780800,754.303223,532.998413,615.070312,737.803406,470673397126,737.803406,2020-12-01
30,1609459200,1467.784912,718.109497,737.708374,1314.986206,1186797483413,1314.986206,2021-01-01
31,1612137600,2036.286499,1274.357788,1314.855225,1416.048950,1007718046121,1416.048950,2021-02-01
32,1614556800,1947.837769,1416.416138,1417.151123,1918.362061,730832219123,1918.362061,2021-03-01
33,1617231600,2797.972412,1912.178467,1919.157227,2773.207031,995334204881,2773.207031,2021-03-31
34,1619823600,4362.350586,1737.468750,2772.838379,2714.945312,1510329786014,2714.945312,2021-04-30
35,1622502000,2891.254883,2315.546631,2707.560547,2517.438721,247616699655,2517.438721,2021-05-31
36,1623213542,2520.206543,2412.197754,2520.206543,2436.194092,37591949312,2436.194092,2021-06-09